# build an executable named myprog from myprog.c

all: CPROG_ex1-24_check_syntax_errors.c
	gcc -g -Wall -o CPROG_ex1-24_check_syntax_errors CPROG_ex1-24_check_syntax_errors.c
clean:
	$(RM) CPROG_ex1-24_check_syntax_errors
run:
	./CPROG_ex1-24_check_syntax_errors
